services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WernerDweight\SpotifyApiClientBundle\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Exception}'

    WernerDweight\SpotifyApiClient\Client\:
        resource: '../../spotify-api-client/src/Client/*'
        exclude: '../../spotify-api-client/src/Client/Abstract*'
        tags:
            - { name: 'spotify_api_client.client' }

    WernerDweight\SpotifyApiClientBundle\Service\ApiFactory:
        arguments:
            $enhancers: !tagged nisi.spotify_api_client.client
